---
version: "2"

services:
  kitchen:
    build:
      context: .
      dockerfile: Dockerfile
    image: kitchen-test:latest
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    privileged: true
    network_mode: host
    command: bundle exec kitchen test
